import glenmarkLogo from "../assets/glenmark.svg"
import abbottLogo from "../assets/abbott.svg"
import patanjaliLogo from "../assets/patanjali.svg"

export const projectCards=[
    {name:"Glenmark",
    logo:glenmarkLogo,
    key:1,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."

},
    {name:"Abbott",
    logo:abbottLogo,
    key:2,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Patanjali",
    key:3,
    logo:patanjaliLogo,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Glenmark",
    logo:glenmarkLogo,
    key:4,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."

},
    {name:"Abbott",
    logo:abbottLogo,
    key:5,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Patanjali",
    key:6,
    logo:patanjaliLogo,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Glenmark",
    logo:glenmarkLogo,
    key:7,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."

},
    {name:"Abbott",
    logo:abbottLogo,
    key:8,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Patanjali",
    key:9,
    logo:patanjaliLogo,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Glenmark",
    logo:glenmarkLogo,
    key:10,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."

},
    {name:"Abbott",
    logo:abbottLogo,
    key:11,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Patanjali",
    key:12,
    logo:patanjaliLogo,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Glenmark",
    logo:glenmarkLogo,
    key:13,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."

},
    {name:"Abbott",
    logo:abbottLogo,
    key:14,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Patanjali",
    key:15,
    logo:patanjaliLogo,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Glenmark",
    logo:glenmarkLogo,
    key:16,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."

},
    {name:"Abbott",
    logo:abbottLogo,
    key:17,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
    {name:"Patanjali",
    key:18,
    logo:patanjaliLogo,
    date:"12/10/2023",
    description:"Glenmark Pharmaceuticals climbs to #2 position for the respiratory segment in the Indian Pharmaceutical Market..."},
]